import {html, LitElement} from './lit.js'

window.teachers = [
  {
    id: 8,
    name: 'Hilale',
    surname: 'Ceferova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Elmerdan',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '2011-08-19T00:00:00',
    email: 'hilale_ceferova@gmail.com',
    phoneNumber: '553139211',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'az', 'en', 'ru', 'tr' ],
    exp: 3
  },
  {
    id: 10,
    name: 'Şahnaz',
    surname: 'Şahbazova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Nadir',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1955-01-31T00:00:00',
    email: 'shahbazova@gmail.com',
    phoneNumber: '503134985',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'az', 'en', 'ru', 'tr' ],
    exp: 15
  },
  {
    id: 11,
    name: 'Heyran',
    surname: 'Həsənova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Rəhim',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1963-12-03T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'en', 'ru' ],
    exp: 6
  },
  {
    id: 12,
    name: 'Aida',
    surname: 'Quliyeva',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Aydın',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1959-08-28T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'az', 'ru' ],
    exp: 1
  },
  {
    id: 13,
    name: 'Sevda',
    surname: 'Bədəlova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Ağababa',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1963-03-17T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'az' ],
    exp: 5
  },
  {
    id: 14,
    name: 'Ceyran',
    surname: 'Xəlilova',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Musa',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1973-08-16T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'en', 'ru' ],
    exp: 10
  },
  {
    id: 15,
    name: 'Dilarə',
    surname: 'Əbdüləziz',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Abas',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1957-01-18T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'ru' ],
    exp: 13
  },
  {
    id: 16,
    name: 'Gülnar',
    surname: 'Mirzəyeva',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Rövşən',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1985-09-23T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'ru', 'tr' ],
    exp: 14
  },
  {
    id: 17,
    name: 'Ülviyyə',
    surname: 'Göyüşova',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Malik',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1996-09-25T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'en', 'ru' ],
    exp: 10
  },
  {
    id: 18,
    name: 'Gülşən',
    surname: 'Fərhadova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Mösüm',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1958-08-20T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'ru', 'tr' ],
    exp: 9
  },
  {
    id: 19,
    name: 'Hafiz',
    surname: 'Bayramov',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Məhərrəv',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1947-06-21T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Informatika uzre felsefe doktoru',
    places: null,
    langs: [ 'en' ],
    exp: 13
  },
  {
    id: 20,
    name: 'Haxverdi',
    surname: 'Mənsimov',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'İsgəndər',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1961-01-10T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'en', 'ru', 'tr' ],
    exp: 1
  },
  {
    id: 21,
    name: 'Həmdulla',
    surname: 'Əsgərov',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Əbil',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1955-05-07T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Texnika Elmleri Namizedi',
    places: null,
    langs: [ 'az', 'en', 'ru' ],
    exp: 8
  },
  {
    id: 22,
    name: 'Aytac',
    surname: 'İbrahimova',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Bahəddin',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1994-03-04T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'en', 'ru' ],
    exp: 9
  },
  {
    id: 23,
    name: 'Fəridə',
    surname: 'İsmayılova',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Səməd',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1989-08-22T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'en' ],
    exp: 2
  },
  {
    id: 24,
    name: 'Abdulla',
    surname: 'Abdullayev',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Xudayət',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1956-11-24T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'en' ],
    exp: 6
  },
  {
    id: 25,
    name: 'Rovsen',
    surname: 'Quliyev',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Agakisi',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1952-10-05T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Texnika Elmleri Namizedi',
    places: null,
    langs: [ 'az' ],
    exp: 4
  },
  {
    id: 26,
    name: 'Arzu',
    surname: 'Məmmədova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'İmamaverdi',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1970-11-06T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az' ],
    exp: 2
  },
  {
    id: 27,
    name: 'Ədalət',
    surname: 'Kərimov',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Kərim',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1954-07-03T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'ru', 'tr' ],
    exp: 5
  },
  {
    id: 28,
    name: 'Arzu',
    surname: 'Əbilova',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Sabir',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1963-08-10T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'ru' ],
    exp: 12
  },
  {
    id: 29,
    name: 'Şamil',
    surname: 'Hümbətov',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Nizaməddin',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1979-02-13T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'ru' ],
    exp: 1
  },
  {
    id: 30,
    name: 'Sonay',
    surname: 'Rezai Vəhid ',
    jobType: 'Tam Ştat',
    scientificName: 'Yoxdur',
    fathername: 'Nader',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1999-03-04T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'en', 'ru', 'tr' ],
    exp: 9
  },
  {
    id: 31,
    name: 'Xaliq',
    surname: 'Pirəlizadə',
    jobType: 'Tam Ştat',
    scientificName: 'Magistr',
    fathername: 'Oqtay',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '1992-07-17T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'ru' ],
    exp: 0
  },
  {
    id: 32,
    name: 'Pərvin',
    surname: 'Cabbarlı',
    jobType: 'Tam Ştat',
    scientificName: 'Magistr',
    fathername: 'Əyyub',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1990-10-31T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Yoxdur',
    places: null,
    langs: [ 'az', 'tr' ],
    exp: 13
  },
  {
    id: 33,
    name: 'Heyran',
    surname: 'Həsənova',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Rəhim',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Qadın',
    birthDate: '1963-12-03T00:00:00',
    email: 'default@gmail.com',
    phoneNumber: '501110011',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'az' ],
    exp: 1
  },
  {
    id: 55,
    name: 'Elvin',
    surname: 'Alizade',
    jobType: 'Tam Ştat',
    scientificName: 'Dosent',
    fathername: 'Vuqar',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '2001-08-19T00:00:00',
    email: 'alizadee13@gmail.com',
    phoneNumber: '703002300',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'ru' ],
    exp: 0
  },
  {
    id: 59,
    name: 'Nurullah',
    surname: 'Memmedov',
    jobType: 'Tam Ştat',
    scientificName: 'Aspirant',
    fathername: 'Ilqar',
    department: 'Rəqəmsal texnologiyalar və tətbiqi informatika',
    sex: 'Kişi',
    birthDate: '2001-11-25T00:00:00',
    email: 'elvin-alizade@outlook.com',
    phoneNumber: '703002300',
    scientificDegree: 'Riyaziyyat uzre Felsefe Doktoru',
    places: null,
    langs: [ 'az' ],
    exp: 1
  }
]

window.finalList = [
    [
        {
            "id": 24,
            "predmetName": "Süni intellekt",
            "code": "00850",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "Y-3",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 21,
            "predmetName": "İnformasiya təhlükəsizliyi",
            "code": "00396",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "Y-3",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 20,
            "predmetName": "Multimediya texnologiyaları",
            "code": "00634",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "P-3",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 22,
            "predmetName": "İnsan-kompüter interfeysi",
            "code": "00426",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "P-3",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 25,
            "predmetName": "Veb sistemləri və texnologiyaları",
            "code": "00914",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "Y-3",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 84,
            "predmetName": "Müasir proqramlaşdırma dilləri ",
            "code": "00092",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "Y-1",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 85,
            "predmetName": "Kompüter arxitekturası",
            "code": "00089",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 8,
            "generalHours": 240,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "Y-1",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 86,
            "predmetName": "Verilənlərin strukturu və alqoritmlər",
            "code": "00924",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "P-2",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 87,
            "predmetName": "Verilənlər bazası sistemləri",
            "code": "00919",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "Y-2",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 88,
            "predmetName": "Əməliyyat sistemləri",
            "code": "00303",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "P-2",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 92,
            "predmetName": "Kompüter şəbəkələri",
            "code": "00490",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 8,
            "generalHours": 240,
            "auditoryHours": 60,
            "categoryId": 3,
            "orderBy": 0,
            "session": "P-2",
            "teacherId": 10
        }
    ],
    [
        {
            "id": 32,
            "predmetName": "Biznes informasiya sistemləri",
            "code": "00196",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 5,
            "generalHours": 150,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 946,
            "session": "P-3",
            "teacherId": 10
        },
        {
            "id": 33,
            "predmetName": "İnformasiya sistemlərinin işlənilməsi",
            "code": "00393",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 5,
            "generalHours": 150,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 946,
            "session": "P-3",
            "teacherId": 0
        },
        {
            "id": 34,
            "predmetName": "İnformasiya sistemlərinin strateji idarə edilməsi ",
            "code": "00395",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 5,
            "generalHours": 150,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 946,
            "session": "P-3",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 38,
            "predmetName": "Müəssisə üçün mobil əlavələrin işlənilməsi",
            "code": "00615",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 183,
            "session": "Y-3",
            "teacherId": 0
        },
        {
            "id": 39,
            "predmetName": "Paralel proqramlaşdırma",
            "code": "00658",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 183,
            "session": "Y-3",
            "teacherId": 0
        },
        {
            "id": 40,
            "predmetName": "Professionallar üçün kiçik biznes ",
            "code": "00674",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 183,
            "session": "Y-3",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 41,
            "predmetName": "Rəqəmsal iqtisadiyyat",
            "code": "00735",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 51,
            "session": "P-3",
            "teacherId": 0
        },
        {
            "id": 42,
            "predmetName": "Rəqəmsal kommunikasiya",
            "code": "00739",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 51,
            "session": "P-3",
            "teacherId": 0
        },
        {
            "id": 43,
            "predmetName": "Rəqəmsal kartoqrafiya və coğrafi informasiya sistemləri ",
            "code": "00737",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 51,
            "session": "P-3",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 44,
            "predmetName": "Maşın təlimi",
            "code": "00540",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 5,
            "generalHours": 150,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 67,
            "session": "Y-3",
            "teacherId": 0
        },
        {
            "id": 45,
            "predmetName": "Verilənlərin təhlükəsizliyi və mühafizəsi",
            "code": "00925",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 5,
            "generalHours": 150,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 67,
            "session": "Y-3",
            "teacherId": 0
        },
        {
            "id": 46,
            "predmetName": "Rəqəmsal kriminalistika ",
            "code": "00740",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 5,
            "generalHours": 150,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 67,
            "session": "Y-3",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 66,
            "predmetName": "İnformasiya texnologiyaları",
            "code": "00402",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 3,
            "generalHours": 90,
            "auditoryHours": 45,
            "categoryId": 2,
            "orderBy": 53,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 67,
            "predmetName": "İnformasiyanın idarə edilməsi",
            "code": "00404",
            "profession": "İnformasiya texnologiyaları",
            "group": "222",
            "course": 3,
            "sector": "Az",
            "credit": 3,
            "generalHours": 90,
            "auditoryHours": 45,
            "categoryId": 2,
            "orderBy": 53,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 135,
            "predmetName": "İnformasiya texnologiyaları",
            "code": "00402",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 3,
            "generalHours": 90,
            "auditoryHours": 45,
            "categoryId": 2,
            "orderBy": 53,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 136,
            "predmetName": "İnformasiyanın idarə edilməsi",
            "code": "00404",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 3,
            "generalHours": 90,
            "auditoryHours": 45,
            "categoryId": 2,
            "orderBy": 53,
            "session": "Y-2",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 97,
            "predmetName": "İstifadəçi interfeysinin dizaynı",
            "code": "00457",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 896,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 98,
            "predmetName": "Kompilyatorlar və interpretatorlar",
            "code": "00475",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 896,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 99,
            "predmetName": "Proqramlaşdırma və problemlərin həlli",
            "code": "00678",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 896,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 100,
            "predmetName": "Alqoritmin analizi və hazırlanması üsulları",
            "code": "00135",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 6,
            "generalHours": 180,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 896,
            "session": "Y-2",
            "teacherId": 0
        }
    ],
    [
        {
            "id": 104,
            "predmetName": "Təhlükəsiz proqramlaşdırma",
            "code": "00868",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 845,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 105,
            "predmetName": "Proqram təminatının keyfiyyəti və testləşdirmə",
            "code": "00675",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 845,
            "session": "Y-2",
            "teacherId": 0
        },
        {
            "id": 106,
            "predmetName": "Obyektyönlü proqramlaşdırma ",
            "code": "00647",
            "profession": "İnformasiya texnologiyaları",
            "group": "111",
            "course": 2,
            "sector": "Ru",
            "credit": 7,
            "generalHours": 210,
            "auditoryHours": 60,
            "categoryId": 4,
            "orderBy": 845,
            "session": "Y-2",
            "teacherId": 0
        }
    ]
]

import "./views/main.js"