let ts = [
    {
        "id": 8,
        "name": "Hilale",
        "surname": "Ceferova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Elmerdan",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "2011-08-19T00:00:00",
        "email": "hilale_ceferova@gmail.com",
        "phoneNumber": "553139211",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 10,
        "name": "Şahnaz",
        "surname": "Şahbazova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Nadir",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1955-01-31T00:00:00",
        "email": "shahbazova@gmail.com",
        "phoneNumber": "503134985",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 11,
        "name": "Heyran",
        "surname": "Həsənova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Rəhim",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1963-12-03T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 12,
        "name": "Aida",
        "surname": "Quliyeva",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Aydın",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1959-08-28T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 13,
        "name": "Sevda",
        "surname": "Bədəlova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Ağababa",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1963-03-17T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 14,
        "name": "Ceyran",
        "surname": "Xəlilova",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Musa",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1973-08-16T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 15,
        "name": "Dilarə",
        "surname": "Əbdüləziz",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Abas",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1957-01-18T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 16,
        "name": "Gülnar",
        "surname": "Mirzəyeva",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Rövşən",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1985-09-23T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 17,
        "name": "Ülviyyə",
        "surname": "Göyüşova",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Malik",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1996-09-25T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 18,
        "name": "Gülşən",
        "surname": "Fərhadova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Mösüm",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1958-08-20T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 19,
        "name": "Hafiz",
        "surname": "Bayramov",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Məhərrəv",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1947-06-21T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Informatika uzre felsefe doktoru",
        "places": null
    },
    {
        "id": 20,
        "name": "Haxverdi",
        "surname": "Mənsimov",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "İsgəndər",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1961-01-10T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 21,
        "name": "Həmdulla",
        "surname": "Əsgərov",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Əbil",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1955-05-07T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Texnika Elmleri Namizedi",
        "places": null
    },
    {
        "id": 22,
        "name": "Aytac",
        "surname": "İbrahimova",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Bahəddin",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1994-03-04T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 23,
        "name": "Fəridə",
        "surname": "İsmayılova",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Səməd",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1989-08-22T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 24,
        "name": "Abdulla",
        "surname": "Abdullayev",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Xudayət",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1956-11-24T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 25,
        "name": "Rovsen",
        "surname": "Quliyev",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Agakisi",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1952-10-05T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Texnika Elmleri Namizedi",
        "places": null
    },
    {
        "id": 26,
        "name": "Arzu",
        "surname": "Məmmədova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "İmamaverdi",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1970-11-06T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 27,
        "name": "Ədalət",
        "surname": "Kərimov",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Kərim",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1954-07-03T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 28,
        "name": "Arzu",
        "surname": "Əbilova",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Sabir",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1963-08-10T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 29,
        "name": "Şamil",
        "surname": "Hümbətov",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Nizaməddin",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1979-02-13T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 30,
        "name": "Sonay",
        "surname": "Rezai Vəhid ",
        "jobType": "Tam Ştat",
        "scientificName": "Yoxdur",
        "fathername": "Nader",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1999-03-04T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 31,
        "name": "Xaliq",
        "surname": "Pirəlizadə",
        "jobType": "Tam Ştat",
        "scientificName": "Magistr",
        "fathername": "Oqtay",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "1992-07-17T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 32,
        "name": "Pərvin",
        "surname": "Cabbarlı",
        "jobType": "Tam Ştat",
        "scientificName": "Magistr",
        "fathername": "Əyyub",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1990-10-31T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Yoxdur",
        "places": null
    },
    {
        "id": 33,
        "name": "Heyran",
        "surname": "Həsənova",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Rəhim",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Qadın",
        "birthDate": "1963-12-03T00:00:00",
        "email": "default@gmail.com",
        "phoneNumber": "501110011",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 55,
        "name": "Elvin",
        "surname": "Alizade",
        "jobType": "Tam Ştat",
        "scientificName": "Dosent",
        "fathername": "Vuqar",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "2001-08-19T00:00:00",
        "email": "alizadee13@gmail.com",
        "phoneNumber": "703002300",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    },
    {
        "id": 59,
        "name": "Nurullah",
        "surname": "Memmedov",
        "jobType": "Tam Ştat",
        "scientificName": "Aspirant",
        "fathername": "Ilqar",
        "department": "Rəqəmsal texnologiyalar və tətbiqi informatika",
        "sex": "Kişi",
        "birthDate": "2001-11-25T00:00:00",
        "email": "elvin-alizade@outlook.com",
        "phoneNumber": "703002300",
        "scientificDegree": "Riyaziyyat uzre Felsefe Doktoru",
        "places": null
    }
]

// for (let t of ts){
//     t.langs =[]
//     if (Math.random()>0.5) t.langs.push('az')
//     if (Math.random()>0.5) t.langs.push('en')
//     if (Math.random()>0.5) t.langs.push('ru')
//     if (Math.random()>0.8) t.langs.push('tr')
// }

// console.log(ts)